// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqlnP2wxXrp1X5PkCaF37G2HGeMSKNqJY',
    appId: '1:609864532278:web:a04f983c9be8e63d927397',
    messagingSenderId: '609864532278',
    projectId: 'todocalendar-21b66',
    authDomain: 'todocalendar-21b66.firebaseapp.com',
    databaseURL: 'https://todocalendar-21b66-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todocalendar-21b66.appspot.com',
    measurementId: 'G-T8ZJJ07TFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbmdA8ZVgBihZ3iPqWJoiKxvmVbRIb_IY',
    appId: '1:609864532278:android:8ecabe2a7009fe38927397',
    messagingSenderId: '609864532278',
    projectId: 'todocalendar-21b66',
    databaseURL: 'https://todocalendar-21b66-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todocalendar-21b66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF78WLJYdUKrM4g2ugIKOrxvFP0lVKrUY',
    appId: '1:609864532278:ios:84ea64f5318547fb927397',
    messagingSenderId: '609864532278',
    projectId: 'todocalendar-21b66',
    databaseURL: 'https://todocalendar-21b66-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todocalendar-21b66.appspot.com',
    iosBundleId: 'com.example.todoCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF78WLJYdUKrM4g2ugIKOrxvFP0lVKrUY',
    appId: '1:609864532278:ios:78847d9c6f5c5ec3927397',
    messagingSenderId: '609864532278',
    projectId: 'todocalendar-21b66',
    databaseURL: 'https://todocalendar-21b66-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todocalendar-21b66.appspot.com',
    iosBundleId: 'com.example.todoCalendar.RunnerTests',
  );
}
